# Generated by Django 5.2.4 on 2025-08-18 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0004_bookdetail_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='library.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('books', models.ManyToManyField(blank=True, related_name='clubs', to='library.book')),
                ('members', models.ManyToManyField(blank=True, related_name='clubs', to='library.borrower')),
            ],
        ),
    ]
